### ISSUE TITLE
Cancellare branch

### ISSUE THREAD

**Issue by samueleCatalano** [GiuseppeCorrao/Flow_Open_Spring#28]
credo che dovremmo cancellare i branch mergiati da tempo

**Comment by francoforte123** [comment]
Penso di sì, visto che sono stati chiusi

**Comment by Waze27** [comment]
👍🏻

**Comment by samueleCatalano** [comment]
li cancelliamo tutti tranne quelli aperti o qualcuno lo lasciamo?

**Comment by francoforte123** [comment]
Cancelliamo quelli mergiati, gli altri che sono aperte li lasciamo aperte

**Comment by GiuseppeCorrao** [comment]
cancellate tutto tranne gli ultimi 3 che non si sa mai

**Comment by GiuseppeCorrao** [comment]
ho cancellato i vari branch
