### ISSUE TITLE
Dubbio sulla classe User

### ISSUE THREAD

**Issue by Waze27** [GiuseppeCorrao/Flow_Open_Spring#3]
Creo questa Issue per utilizzare GitHub ed esporvi un dubbio sull'enitity User.

Nella classe ci sono gli attributi segnati come @NonNull:
![image](https://user-images.githubusercontent.com/110262144/196155357-6bcb1993-7a31-44bb-9a00-6987322f4216.png)

Non sarebbe meglio utilizzare una dicitura più corretta ed inerente al DB come questa? :
![image](https://user-images.githubusercontent.com/110262144/196155822-c7e2a5c8-02f5-466c-9b1b-95acf6f61b96.png)

Fatemi sapere ragazzi, in caso può tranquillamente modificarla @samueleCatalano che ha creato la PR.
Scusatemi se non me ne sono accorto prima.

**Comment by samueleCatalano** [comment]
> Creo questa Issue per utilizzare GitHub ed esporvi un dubbio sull'enitity User.
> 
> Nella classe ci sono gli attributi segnati come @nonnull: ![image](https://user-images.githubusercontent.com/110262144/196155357-6bcb1993-7a31-44bb-9a00-6987322f4216.png)
> 
> Non sarebbe meglio utilizzare una dicitura più corretta ed inerente al DB come questa? : ![image](https://user-images.githubusercontent.com/110262144/196155822-c7e2a5c8-02f5-466c-9b1b-95acf6f61b96.png)
> 
> Fatemi sapere ragazzi, in caso può tranquillamente modificarla @samueleCatalano che ha creato la PR. Scusatemi se non me ne sono accorto prima.

ci sta. creo un'altra PR per sta cosa o magari lo faccio direttamente dal main?
